stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "No build step needed for static files"

deploy:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
